config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end 

  devise_for :users

  resources :charges

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy

  before_save { self.email = email.downcase if email.present? }
  after_initialize :initialize_role

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email, presence: true, uniqueness: { case_sensitive: false },length: { minimum: 3, maximum: 254 }

  enum role: [:standard, :premium, :admin]

  private

  def initialize_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    if current_user.admin?
      redirect_to edit_user_registration_path(current_user)
    end

   @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Upgrade to Premium",
     amount: amount
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attribute(:role, 'premium')

    flash[:notice] = "Congrats, #{current_user.email}! Your account has been upgraded to premium."
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def destroy
    if current_user.transaction do
      current_user.standard!
      current_user.wikis.update_all(private: false)
    end
    flash[:notice] = "You have successfully downgraded your account."
    else
    flash[:notice] = "There was an error downgrading your account."
    end
    redirect_to root_path
  end

  private

  def amount
    15_00
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator_user = User.find_by_email(params[:collaborator])
    @wiki = Wiki.find(params[:wiki_id])

    if !@collaborator_user
      flash[:alert] = "That user does not exist. Please try again."
      redirect_to @wiki
    elsif @wiki.collaborators.exists?(user_id: @collaborator_user.id)
      flash[:notice] = "#{@collaborator_user.email} is already a collaborator."
      redirect_to @wiki
    else
      @collaborator = Collaborator.new(user_id: @collaborator_user.id, wiki: @wiki)

      if @collaborator.save
        flash[:notice] = "Collaborator was saved."
        redirect_to @wiki
      else
        flash.now[:alert] = "There was an error saving the collaborator."
        redirect_to @wiki
      end
    end
  end

    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = Collaborator.find(params[:id])
        @collaborator_user = User.find(@collaborator.user_id)

        if @collaborator.destroy
          flash[:notice] = "Collaborator was deleted."
          redirect_to @wiki
        else
          flash.now[:alert] = "There was an error deleting the collaborator."
          redirect_to @wiki
        end
      end
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    if current_user && current_user.premium? || current_user && current_user.admin?
      @wikis = Wiki.all
    else
      @wikis = Wiki.where(private: false)
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:alert] = "There was an error updating the wiki. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end  
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="col-md-8">
  <div class="row">
    <h1>My Account</h1>
    <hr>
    <h3>Current Status: <%= current_user.role.capitalize %></h3>
    <br>
      <%= form_tag charges_path do %>
      <% if current_user.role == 'premium' %>
          <p>Downgrading your account will restrict access to private wikis, and any private wikis you have created will be made public.</p>
          <br>
          <%= link_to "Downgrade Account", @charge, method: :delete, class: 'btn btn-delete', data: { confirm: 'Are you sure you want to downgrade your account?' } %>
        <% elsif current_user.role == 'standard' %>
          <h4>Upgrade to Premium</h4>
          <p>A fee of $15 will give access to private wikis.</p>
          <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>

app/views/collaborators/_form.html.erb
<div class="form-group">
    <% if current_user.premium? || current_user.admin? %>
    <div>
      <hr>
      <h3>Add Collaborators</h3>
        <%= form_for [@wiki, Collaborator.new] do |c| %>
        <%= email_field_tag :collaborator %>
        <%= c.submit "Add collaborator", class: 'btn btn-default btn-collab' %>
    <% end %>
    <hr>
    <h3>Manage Collaborators</h3>
    <% wiki.collaborators.each do |c| %>
      <% user = User.find(c.user_id) %>
      <%= user.email %>
      <%= link_to "Delete", wiki_collaborator_path(@wiki, c), class: 'btn btn-delete', method: :delete%>
    <% end %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wisegui</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Crimson+Text:400,600,700" rel="stylesheet' %>
    <%= stylesheet_link_tag 'application', 'https://use.fontawesome.com/releases/v5.7.2/css/all.css' %>
  </head>

  <body>

    <div class="pull-right sign-in">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'EDIT PROFILE', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "SIGN UP", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "SIGN IN", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <div>
      <ul class="nav nav-tabs">
        <li class="wisegui-nav"><%= link_to "WISEGUI", root_path %></li>
        <li><%= link_to "WIKIS", wikis_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "MANAGE ACCOUNT", new_charge_path%></li>
      <%end%>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="title wisegui"><span class="w">W</span>ISEGU<span class="i">I</span></h1>
  <p class="title wisegui-desc">An opensource online encyclopedia</p>
</div>

<div class="row home-pg">
  <div class="home col-md-4">
    <h2><i class="fas fa-lightbulb"></i></i>Create</h2>
    <p>Post public wikis about the topics you care about</p>
  </div>
  <div class="home col-md-4">
    <h2><i class="fas fa-dollar-sign"></i>Upgrade</h2>
    <p>Premium account holders can share private wikis</p>
  </div>
  <div class="home col-md-4">
    <h2><i class="fas fa-hands-helping"></i>Collaborate</h2>
    <p>Share wikis by collaborating with other users</p>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-delete">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="col-md-8">
  <div class="row">
    <h1>Edit Wiki</h1>
    <br>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <%= render partial: 'collaborators/form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="col-md-8">
  <h1 class="title">
    All Wikis
  </h1>
  <br>
  <div class="new-wiki">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default' %>
  </div>
  <br>
  <% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
        <hr>
      </h4>
    </div>
  </div>
  <% end %>
</div>

app/views/wikis/new.html.erb
<div class="col-md-8">
  <div class="row">
    <h1>New Wiki</h1>
    <br>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
  <div class="col-md-8">
    <div class="row">
      <h1><%= @wiki.title %></h1
      <p><%= markdown(@wiki.body) %></p>
    </div>
    <br>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-default' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-delete', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <div>
      <% if current_user.premium? || current_user.admin? %>
      <hr>
      <h3>Collaborators</h3>
      <% if @wiki.collaborators.any? %>
        <% @wiki.collaborators.each do |c| %>
          <% user = User.find(c.user_id) %>
          <%= user.email %>
        <% end %>
        <% else %>
          <p>This post doesn't have any collaborators yet.</p>
        <% end %>
     <% end %>
   </div>
</div>